### ISSUE TITLE
avoid temp overshoot

### ISSUE THREAD

**Issue by derFliegendeHamburger** [werner-rh/drybox-control#1]
as general safety measure or if heater runs during ventilation phase, the temp could rise way above the desired target drying temperature.
cure: add a test and emergency stop for the heater  right after reading the sensor.

**Comment by werner-rh** [comment]
The heater only runs until the destination temperature is reached. Then it is switched off. The heater also don't run during ventilation. After switch off the heater doesn't cool down immediately. So the temperature may increase a lttle bit over the destination. This is a normal Hysteresis in temperature controll processes.

Anyway, the heater is a PTC element. It can't overheat.

**Comment by werner-rh** [comment]
There is no need for an emergency stop within the normal Hysteresis. The temperature is reading as fast as the DHT11 is able to deliver and the values are immediately handled.

**Comment by werner-rh** [comment]
Solution: add the marked line to the code
      case DST_AIR_EXCHANGE:
        if(airExChgOneMinuteCounter > 0) {
          airExChgOneMinuteCounter--;
        } else {
          airExChgOneMinuteCounter = 6000; //set for next count
          airExChgMinutesCounter = 0;
          **SetPWMRate(HEATING_PIN, 0); // heater has to switch off. Otherwise the temp will continue to raise up** 
          SetPWMRate(FANAIR_PIN, 0);
          DryState = DST_TEMP_REACHED;
        }
        break;
