### ISSUE TITLE
Encoder Button not configured

### ISSUE THREAD

**Issue by bmchughs** [werner-rh/drybox-control#16]
I had issue with the Arduino sketch, specifically the encoder 'button' was not working.  Looking at the sketch I included the code below on line 157 and it resolved the issue.

` pinMode(EncSwitch, INPUT_PULLUP);`

I don't see that the 'EncSwitch' was configured to be an 'input' anywhere in the sketch.  Once I included this bit of code, it worked perfectly fine.

**Comment by werner-rh** [comment]
Yes you are right. I found it now. But i don't know why, my Encoder works fine even without the input config ;) - i will fix it.

**Comment by werner-rh** [comment]
Fixed in v0.49.1
