### ISSUE TITLE
timing is wrong by factor 2

### ISSUE THREAD

**Issue by derFliegendeHamburger** [werner-rh/drybox-control#2]
in my setup I have to half the timing counters from 100 down to 50 and from 6000 down to 3000 respectively to get proper timing

**Comment by werner-rh** [comment]
there might be something wrong on your side. The timing is controlled by interrupt in chain of the milli second timer. My timing fits like a swiss clock. Are you using something different? Usb serial or some other thing?

**Comment by derFliegendeHamburger** [comment]
different hardware, yes. For arduino software relevant differences are
i2c sensor SHT41, 4-pin pwm fans require 4kHz pwm signal, 20x4 display, usb debug output.

**Comment by werner-rh** [comment]
The usb debug output might crash your timing. Have you tried it without usb serial output?

**Comment by derFliegendeHamburger** [comment]
yes, no difference.
I can see my other problem related to timing - the display gets garbled. From past projects I know this happens when the display (driver and or firmware and or hardware) suffers from too frequent requests. 
Not sure if the 20x04 display is particularly slow but I like the extra space for output.
It will take some more time to diagnose this further and possibly adopt code accordingly.

**Comment by werner-rh** [comment]
I never tried a 20x4 until now. The two lines more might be the problem, because they are forcing a lot more traffic on the I2C. Even with the 16x2 display, only particluar ranges are updated, because this also needs a lot of time. Maybe you can use a parallel interface for the display. That would be much faster. The DryBox it self doesn't need much I/Os.

**Comment by derFliegendeHamburger** [comment]
- reduced i2c bus speed to 100kHz,
- replaced 4wire ribbon cable for  i2c wiring to i2c sensor sht41 with shorter CAT5 shielded cable
working, solved

**Comment by werner-rh** [comment]
Sounds good! Great!
