### ISSUE TITLE
Question wrt to ventilation cycle

### ISSUE THREAD

**Issue by derFliegendeHamburger** [werner-rh/drybox-control#6]
in the process of drying, the ventilation is activated every 4 minutes with 20 seconds runtime.
Are these specifics accidental or do you have any 'theory' or testing scheme behind this?

Reason for me asking is that my drybox is built to hold 4Kg spools, so it is quite larger and holds more air and more mass than the typical dryer.

**Comment by werner-rh** [comment]
The interval of 4 minutes and 20 seconds are evaluated with the 10L Box. In combination i had a good ventilation for this box and not to much temperature drop. For a 4kg spool, your box must be quite bigger. So you have to find out, which are the best parameter. Take a look at version 0.48. I have refactored the code a bit and you now have all adjustable parameter at one place in file HeatinData.cpp. This might be easier to try out the parameters you need.

**Comment by werner-rh** [comment]
can be closed
